# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'SocialMeetUp' do

  use_frameworks!

  # Pods for SocialMeetUp
        pod 'Firebase/Analytics'
        pod 'Firebase/Auth'
        pod 'GoogleMaps'
        pod 'GooglePlaces'
        pod 'SkyFloatingLabelTextField', '~> 3.0'
        #pod 'Hero'
end
