# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Plexus' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Plexus
    pod 'Firebase/Analytics'
    pod 'Firebase/Auth'
    pod 'SkyFloatingLabelTextField', '~> 3.0'
    pod 'ActiveLabel'
end
