//
//  ExamInteractor.swift
//  Plexus
//
//  Created Anik on 19/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ExamInteractor: ExamInteractorProtocol {

    weak var presenter: ExamPresenterProtocol?
}
