//
//  ExamPresenter.swift
//  Plexus
//
//  Created Anik on 19/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ExamPresenter: ExamPresenterProtocol {

    weak private var view: ExamViewProtocol?
    var interactor: ExamInteractorProtocol?
    private let router: ExamWireframeProtocol

    init(interface: ExamViewProtocol, interactor: ExamInteractorProtocol?, router: ExamWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
