//
//  ExamProtocols.swift
//  Plexus
//
//  Created Anik on 19/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ExamWireframeProtocol: class {

}
//MARK: Presenter -
protocol ExamPresenterProtocol: class {

}

//MARK: Interactor -
protocol ExamInteractorProtocol: class {

  var presenter: ExamPresenterProtocol?  { get set }
}

//MARK: View -
protocol ExamViewProtocol: class {

  var presenter: ExamPresenterProtocol?  { get set }
}
