//
//  HomeRouter.swift
//  Plexus
//
//  Created Anik on 16/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeRouter: HomeWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(view: HomeViewController) {
        // Change to get view from storyboard if not using progammatic UI
        let interactor: HomeInteractorProtocol & HomeDataManagerOutputProtocol = HomeInteractor()
        let router = HomeRouter()
        let presenter: HomePresenterProtocol & HomeInteractorOutputProtocol = HomePresenter(interface: view, interactor: interactor, router: router)
        let remoteDataManager: HomeDataManagerInputProtocol = HomeDataManager()
        
        view.presenter = presenter
        //interactor.presenter = presenter
        interactor.interactorOutput = presenter
        interactor.datamanager = remoteDataManager as? HomeDataManager
        router.viewController = view
        remoteDataManager.remoteRequestHandler = interactor
    }
}
