//
//  HomeInteractor.swift
//  Plexus
//
//  Created Anik on 16/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeInteractor: HomeInteractorProtocol {
    weak var presenter: HomePresenterProtocol?
    var interactorOutput: HomeInteractorOutputProtocol?
    var datamanager: HomeDataManagerInputProtocol?
    
    func retrieveHomeCourses() {
        datamanager?.retrieveHomeCourses()
    }
}

extension HomeInteractor: HomeDataManagerOutputProtocol {
    func onHomeCoursesRetrieved(_ courses: CourseRequest) {
        interactorOutput?.didRetrieveHomeCourses(courses)
    }
    
    func onError() {
        
    }
}
