//
//  HomePresenter.swift
//  Plexus
//
//  Created Anik on 16/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomePresenter: HomePresenterProtocol {

    weak private var view: HomeViewProtocol?
    var interactor: HomeInteractorProtocol?
    private let router: HomeWireframeProtocol

    init(interface: HomeViewProtocol, interactor: HomeInteractorProtocol?, router: HomeWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func viewDidLoad() {
        view?.showLoading()
        interactor?.retrieveHomeCourses()
    }
}

extension HomePresenter: HomeInteractorOutputProtocol {
    func didRetrieveHomeCourses(_ courses: CourseRequest) {
        view?.hideLoading()
        view?.showHomeCourses(with: courses)
    }
    
    func onError() {
        view?.hideLoading()
        view?.showError()
    }
}
