//
//  CongratsPresenter.swift
//  Plexus
//
//  Created Anik on 23/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CongratsPresenter: CongratsPresenterProtocol {

    weak private var view: CongratsViewProtocol?
    var interactor: CongratsInteractorProtocol?
    private let router: CongratsWireframeProtocol

    init(interface: CongratsViewProtocol, interactor: CongratsInteractorProtocol?, router: CongratsWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
