//
//  CongratsProtocols.swift
//  Plexus
//
//  Created Anik on 23/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol CongratsWireframeProtocol: class {

}
//MARK: Presenter -
protocol CongratsPresenterProtocol: class {

}

//MARK: Interactor -
protocol CongratsInteractorProtocol: class {

  var presenter: CongratsPresenterProtocol?  { get set }
}

//MARK: View -
protocol CongratsViewProtocol: class {

  var presenter: CongratsPresenterProtocol?  { get set }
}
