//
//  CongratsViewController.swift
//  Plexus
//
//  Created Anik on 23/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CongratsViewController: UIViewController, CongratsViewProtocol {

    @IBOutlet weak var confettiImageView: UIImageView!
    @IBOutlet weak var boxImageView: UIImageView!
    
    var presenter: CongratsPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

    @IBAction func proceedButtonClicked(_ sender: Any) {
    }
}
