//
//  ForgotPasswordInteractor.swift
//  Plexus
//
//  Created Anik on 16/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ForgotPasswordInteractor: ForgotPasswordInteractorProtocol {

    weak var presenter: ForgotPasswordPresenterProtocol?
}
