//
//  ForgotPasswordPresenter.swift
//  Plexus
//
//  Created Anik on 16/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ForgotPasswordPresenter: ForgotPasswordPresenterProtocol {

    weak private var view: ForgotPasswordViewProtocol?
    var interactor: ForgotPasswordInteractorProtocol?
    private let router: ForgotPasswordWireframeProtocol

    init(interface: ForgotPasswordViewProtocol, interactor: ForgotPasswordInteractorProtocol?, router: ForgotPasswordWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
