//
//  ForgotPasswordProtocols.swift
//  Plexus
//
//  Created Anik on 16/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ForgotPasswordWireframeProtocol: class {

}
//MARK: Presenter -
protocol ForgotPasswordPresenterProtocol: class {

}

//MARK: Interactor -
protocol ForgotPasswordInteractorProtocol: class {

  var presenter: ForgotPasswordPresenterProtocol?  { get set }
}

//MARK: View -
protocol ForgotPasswordViewProtocol: class {

  var presenter: ForgotPasswordPresenterProtocol?  { get set }
}
