//
//  TestViewController.swift
//  Plexus
//
//  Created Anik on 23/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TestViewController: UIViewController, TestViewProtocol, UITextViewDelegate {

	var presenter: TestPresenterProtocol?

    @IBOutlet weak var progressBar: UIProgressView!
    @IBOutlet weak var answerTextView: UITextView!
    @IBOutlet weak var submitButton: UIButton!
    var examTimeRemainingCounter = 571
    var timerForTest = Timer()
    
    var initialTotalTime : Int = 1
    
	override func viewDidLoad() {
        super.viewDidLoad()
        initialTotalTime = examTimeRemainingCounter
        answerTextView.delegate = self
        startExamTimer()
    }

    @IBAction func backButtonClicked(_ sender: Any) {
        navigationController!.popViewController(animated: true)
    }
    
    fileprivate func startExamTimer() {
        timerForTest.invalidate() // just in case this button is tapped multiple times
        // start the timer
        timerForTest = Timer.scheduledTimer(timeInterval: 0.1, target: self, selector: #selector(examTimerAction), userInfo: nil, repeats: true)
        RunLoop.main.add(timerForTest, forMode: RunLoop.Mode.common)
    }
    
    @objc func examTimerAction() {
        if examTimeRemainingCounter > 0 {
            examTimeRemainingCounter -= 1
            
            let progress = 1 - (Float(examTimeRemainingCounter) / Float(initialTotalTime))
            progressBar.setProgress(progress, animated: true)
        } else {
            timerForTest.invalidate()
            //go back to basic callback
            answerTextView.isEditable = false
            submitButton.isHidden = false
        }
    }
    
    func textViewDidBeginEditing(_ textView: UITextView) {
        submitButton.isHidden = false
    }
    
    @IBAction func submitAnswerClicked(_ sender: Any) {
        let storyBoard: UIStoryboard = UIStoryboard(name: "Exam", bundle: nil)
        let congratsViewController = storyBoard.instantiateViewController(withIdentifier: "congratsView") as! CongratsViewController
        self.show(congratsViewController, sender: nil)
    }
}
