//
//  TestPresenter.swift
//  Plexus
//
//  Created Anik on 23/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TestPresenter: TestPresenterProtocol {

    weak private var view: TestViewProtocol?
    var interactor: TestInteractorProtocol?
    private let router: TestWireframeProtocol

    init(interface: TestViewProtocol, interactor: TestInteractorProtocol?, router: TestWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
