//
//  TestProtocols.swift
//  Plexus
//
//  Created Anik on 23/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol TestWireframeProtocol: class {

}
//MARK: Presenter -
protocol TestPresenterProtocol: class {

}

//MARK: Interactor -
protocol TestInteractorProtocol: class {

  var presenter: TestPresenterProtocol?  { get set }
}

//MARK: View -
protocol TestViewProtocol: class {

  var presenter: TestPresenterProtocol?  { get set }
}
