//
//  UserLevelProtocols.swift
//  Plexus
//
//  Created Anik on 23/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol UserLevelWireframeProtocol: class {

}
//MARK: Presenter -
protocol UserLevelPresenterProtocol: class {

}

//MARK: Interactor -
protocol UserLevelInteractorProtocol: class {

  var presenter: UserLevelPresenterProtocol?  { get set }
}

//MARK: View -
protocol UserLevelViewProtocol: class {

  var presenter: UserLevelPresenterProtocol?  { get set }
}
