//
//  UserLevelViewController.swift
//  Plexus
//
//  Created Anik on 23/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class UserLevelViewController: UIViewController, UserLevelViewProtocol {

    @IBOutlet weak var desiredLevelTableView: UITableView!
    var presenter: UserLevelPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        setupViews()
    }
    
    private func setupViews() {
        desiredLevelTableView.delegate = self
        desiredLevelTableView.dataSource = self
        desiredLevelTableView.register(UINib(nibName: "DesiredLevelCell", bundle: nil), forCellReuseIdentifier: "desiredCell")
    }
    
    @IBAction func backButtonClicked(_ sender: Any) {
        navigationController!.popViewController(animated: true)
    }

}

extension UserLevelViewController: UITableViewDelegate, UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        var cellWidth : CGFloat = 107.0;
        
        if indexPath.row == 4 {
            cellWidth = 47.0
        }
        return cellWidth;
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 5
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "desiredCell", for: indexPath) as! DesiredLevelCell
        cell.layer.backgroundColor = UIColor.clear.cgColor
        return cell
    }
}
