//
//  WishlistInteractor.swift
//  Plexus
//
//  Created Anik on 19/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WishlistInteractor: WishlistInteractorProtocol {

    var interactorOutput: WishlistInteractorOutputProtocol?
    var datamanager: WishlistDataManagerInputProtocol?
    weak var presenter: WishlistPresenterProtocol?
    func retrieveWishlistCourses() {
        datamanager?.retrieveWishlistCourses()
    }
    
}

extension WishlistInteractor: WishlistDataManagerOutputProtocol {
    func onWishlistCoursesRetrieved(_ courses: [WishlistRequest]) {
        interactorOutput?.didRetrieveWishlistCourses(courses)
    }
    
    func onError() {
        
    }
}
