//
//  WishlistInteractor.swift
//  Plexus
//
//  Created Anik on 19/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WishlistInteractor: WishlistInteractorProtocol {

    weak var presenter: WishlistPresenterProtocol?
}
