//
//  WishlistProtocols.swift
//  Plexus
//
//  Created Anik on 19/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol WishlistWireframeProtocol: class {

}
//MARK: Presenter -
protocol WishlistPresenterProtocol: class {

}

//MARK: Interactor -
protocol WishlistInteractorProtocol: class {

  var presenter: WishlistPresenterProtocol?  { get set }
}

//MARK: View -
protocol WishlistViewProtocol: class {

  var presenter: WishlistPresenterProtocol?  { get set }
}
