//
//  WishlistRouter.swift
//  Plexus
//
//  Created Anik on 19/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WishlistRouter: WishlistWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(view: WishlistViewController) {
        // Change to get view from storyboard if not using progammatic UI
        let interactor: WishlistInteractorProtocol & WishlistDataManagerOutputProtocol = WishlistInteractor()
        let router = WishlistRouter()
        let presenter: WishlistPresenterProtocol & WishlistInteractorOutputProtocol = WishlistPresenter(interface: view, interactor: interactor, router: router)
        let remoteDataManager: WishlistDataManagerInputProtocol = WishlistDataManager()
        
        view.presenter = presenter
        interactor.interactorOutput = presenter
        interactor.datamanager = remoteDataManager as? WishlistDataManager
        interactor.presenter = presenter
        router.viewController = view
        remoteDataManager.remoteRequestHandler = interactor
    }
}
