//
//  WishlistPresenter.swift
//  Plexus
//
//  Created Anik on 19/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WishlistPresenter: WishlistPresenterProtocol {

    weak private var view: WishlistViewProtocol?
    var interactor: WishlistInteractorProtocol?
    private let router: WishlistWireframeProtocol

    init(interface: WishlistViewProtocol, interactor: WishlistInteractorProtocol?, router: WishlistWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func viewDidLoad() {
        view?.showLoading()
        interactor?.retrieveWishlistCourses()
    }
}

extension WishlistPresenter: WishlistInteractorOutputProtocol {
    func didRetrieveWishlistCourses(_ courses: [WishlistRequest]) {
        view?.hideLoading()
        view?.showWishlistCourses(with: courses)
    }
    
    func onError() {
        view?.hideLoading()
        view?.showError()
    }
}
