//
//  LessonInteractor.swift
//  Plexus
//
//  Created Anik on 23/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LessonInteractor: LessonInteractorProtocol {

    weak var presenter: LessonPresenterProtocol?
}
