//
//  LessonPresenter.swift
//  Plexus
//
//  Created Anik on 23/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LessonPresenter: LessonPresenterProtocol {

    weak private var view: LessonViewProtocol?
    var interactor: LessonInteractorProtocol?
    private let router: LessonWireframeProtocol

    init(interface: LessonViewProtocol, interactor: LessonInteractorProtocol?, router: LessonWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
