//
//  LessonProtocols.swift
//  Plexus
//
//  Created Anik on 23/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol LessonWireframeProtocol: class {

}
//MARK: Presenter -
protocol LessonPresenterProtocol: class {

}

//MARK: Interactor -
protocol LessonInteractorProtocol: class {

  var presenter: LessonPresenterProtocol?  { get set }
}

//MARK: View -
protocol LessonViewProtocol: class {

  var presenter: LessonPresenterProtocol?  { get set }
}
