//
//  LessonViewController.swift
//  Plexus
//
//  Created Anik on 23/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LessonViewController: UIViewController, LessonViewProtocol {

	var presenter: LessonPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

    @IBAction func backButtonClicked(_ sender: Any) {
        navigationController!.popViewController(animated: true)
    }
    
    @IBAction func startExamButtonClicked(_ sender: Any) {
        let storyBoard: UIStoryboard = UIStoryboard(name: "Exam", bundle: nil)
        let desiredLevelViewController = storyBoard.instantiateViewController(withIdentifier: "userLevelView") as! UserLevelViewController
        self.show(desiredLevelViewController, sender: nil)
    }
    
}
