//
//  LessonViewController.swift
//  Plexus
//
//  Created Anik on 23/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LessonViewController: UIViewController, LessonViewProtocol, UITextViewDelegate {
    
    @IBOutlet weak var startExamButton: UIButton!
    @IBOutlet weak var lessonTextView: UITextView!
    @IBOutlet weak var lessonBackgroundView: UIImageView!
    var presenter: LessonPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        lessonTextView.delegate = self
        resetViewTransform()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        UIView.animate(withDuration: 0.5, delay: 0.1, usingSpringWithDamping: 0.7, initialSpringVelocity: 1, options: .curveEaseIn, animations: {
            self.lessonBackgroundView.transform = CGAffineTransform(scaleX: 1, y: 1)
            self.lessonBackgroundView.alpha = 1
            
        }, completion: nil )
    }
    
    override func viewDidDisappear(_ animated: Bool) {
        super.viewDidDisappear(animated)
        resetViewTransform()
    }

    @IBAction func backButtonClicked(_ sender: Any) {
        navigationController!.popViewController(animated: true)
    }
    
    @IBAction func startExamButtonClicked(_ sender: Any) {
        let storyBoard: UIStoryboard = UIStoryboard(name: "Exam", bundle: nil)
        let desiredLevelViewController = storyBoard.instantiateViewController(withIdentifier: "userLevelView") as! UserLevelViewController
        self.show(desiredLevelViewController, sender: nil)
    }
    
    func resetViewTransform() {
        self.lessonBackgroundView.alpha = 0
        self.lessonBackgroundView.transform = CGAffineTransform(scaleX: 0.5, y: 0.5)
    }
    
    func scrollViewDidScroll(_ scrollView: UIScrollView) {
        startExamButton.isHidden = scrollView.contentOffset.y + scrollView.bounds.height < scrollView.contentSize.height
    }
    
}
