//
//  OnlineViewController.swift
//  Plexus
//
//  Created Anik on 19/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import Firebase

class OnlineViewController: UIViewController, OnlineViewProtocol {

    @IBOutlet weak var courseCollectionView: UICollectionView!
    var presenter: OnlinePresenterProtocol?
    private let networkManager: NetworkManager = NetworkManager()
    private var onlineCourselist: [OnlineRequest] = []

	override func viewDidLoad() {
        super.viewDidLoad()
        
        setupViews()
        /*
        let db = Firestore.firestore()
        db.collection("OnlineCourses").getDocuments() { (querySnapshot, err) in
            if let err = err {
                print("Error getting documents: \(err)")
            } else {
                for document in querySnapshot!.documents {
                    print("\(document.documentID) => \(document.data())")
                }
            }
        }
 */
    }
    
    private func setupViews() {
        self.showWaitView(onView: self.view)
        networkManager.getOnlineRequest( completion: { (onlineRequest) in
            self.onlineCourselist = onlineRequest!
            self.removeWaitView()
            self.courseCollectionView.reloadData()
        })
    }

}

extension OnlineViewController: UICollectionViewDelegate, UICollectionViewDataSource{
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "onlineCourseCell", for: indexPath) as! OnlineCoursesCell
        if onlineCourselist.count > 0 {
            cell.alpha = 0
            let cellDelay = UInt64((arc4random() % 600 ) / 1000 )
            let cellDelayTime = DispatchTime(uptimeNanoseconds: cellDelay * NSEC_PER_SEC)
            DispatchQueue.main.asyncAfter(deadline: cellDelayTime) {
                UIView.animate(withDuration: 0.8, animations: {
                    cell.alpha = 1.0
                })
            }
            
            let course = onlineCourselist[indexPath.row]
            cell.courseImageView.image = UIImage(named: course.imageName!)
            cell.courseTitleLabel.text = course.title
        }
        
        return cell
    }
    
    
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return onlineCourselist.count
    }
}
