//
//  OnlineInteractor.swift
//  Plexus
//
//  Created Anik on 19/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class OnlineInteractor: OnlineInteractorProtocol {
    var interactorOutput: OnlineInteractorOutputProtocol?
    var datamanager: OnlineDataManagerInputProtocol?
    weak var presenter: OnlinePresenterProtocol?
    
    func retrieveOnlineCourses() {
        datamanager?.retrieveOnlineCourses()
    }
}

extension OnlineInteractor: OnlineDataManagerOutputProtocol {
    func onOnlineCoursesRetrieved(_ courses: [OnlineRequest]) {
        interactorOutput?.didRetrieveOnlineCourses(courses)
    }
    
    func onError() {
        
    }
}
