//
//  ProfileViewController.swift
//  Plexus
//
//  Created Anik on 19/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ProfileViewController: UIViewController, ProfileViewProtocol {

    @IBOutlet weak var profilePictureImageView: UIImageView!
    @IBOutlet weak var profileCoursesTableview: UITableView!
    var presenter: ProfilePresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        resetViewTransform()
        setupViews()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        UIView.animate(withDuration: 0.5, delay: 0.1, usingSpringWithDamping: 0.7, initialSpringVelocity: 1, options: .curveEaseIn, animations: {
            self.profilePictureImageView.transform = CGAffineTransform(scaleX: 1, y: 1)
            self.profilePictureImageView.alpha = 1
            
        }, completion: nil )
    }
    
    override func viewDidDisappear(_ animated: Bool) {
        super.viewDidDisappear(animated)
        resetViewTransform()
    }
    
    private func setupViews() {
        profileCoursesTableview.delegate = self
        profileCoursesTableview.dataSource = self
    }
    
    func resetViewTransform() {
        self.profilePictureImageView.alpha = 0
        self.profilePictureImageView.transform = CGAffineTransform(scaleX: 0.5, y: 0.5)
    }

}

extension ProfileViewController: UITableViewDelegate, UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        var cellWidth : CGFloat = 179.0;
        if indexPath.row == 1 {
            cellWidth = 198.0
        }
        return cellWidth;
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 2
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if indexPath.row == 1 {
            let cell = tableView.dequeueReusableCell(withIdentifier: "topRatedParentCell", for: indexPath) as! TopRatedParentCell
            cell.layer.backgroundColor = UIColor.clear.cgColor
            return cell
        } else {
            let cell = tableView.dequeueReusableCell(withIdentifier: "completedParentCell", for: indexPath) as! CompletedParentCell
            cell.layer.backgroundColor = UIColor.clear.cgColor
            return cell
        }
        
    }
}
