//
//  ProfileRouter.swift
//  Plexus
//
//  Created Anik on 19/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ProfileRouter: ProfileWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(view: ProfileViewController) {
        // Change to get view from storyboard if not using progammatic UI
        let interactor: ProfileInteractorProtocol & ProfileDataManagerOutputProtocol = ProfileInteractor()
        let router = ProfileRouter()
        let presenter: ProfilePresenterProtocol & ProfileInteractorOutputProtocol = ProfilePresenter(interface: view, interactor: interactor, router: router)
        let remoteDataManager: ProfileDataManagerInputProtocol = ProfileDataManager()
        
        view.presenter = presenter
        interactor.interactorOutput = presenter
        interactor.datamanager = remoteDataManager as? ProfileDataManager
        interactor.presenter = presenter
        router.viewController = view
        remoteDataManager.remoteRequestHandler = interactor
    }
}
