//
//  SignInProtocols.swift
//  Plexus
//
//  Created Anik on 16/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SignInWireframeProtocol: class {

}
//MARK: Presenter -
protocol SignInPresenterProtocol: class {

}

//MARK: Interactor -
protocol SignInInteractorProtocol: class {

  var presenter: SignInPresenterProtocol?  { get set }
}

//MARK: View -
protocol SignInViewProtocol: class {

  var presenter: SignInPresenterProtocol?  { get set }
}
