//
//  SignInRouter.swift
//  Plexus
//
//  Created Anik on 16/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignInRouter: SignInWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(view: SignInViewController) {
        // Change to get view from storyboard if not using progammatic UI
        let interactor = SignInInteractor()
        let router = SignInRouter()
        let presenter = SignInPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
    }
    
    func showTabMenuScreen(from view: SignInViewProtocol) {
        let storyboard = UIStoryboard(name: "TabMenu", bundle: nil)
        let vc = storyboard.instantiateViewController(withIdentifier: "tabMenuController") as! MenuViewController
        if let sourceView = view as? UIViewController {
            sourceView.show(vc, sender: nil)
        }
        
    }
}
