//
//  SignInViewController.swift
//  Plexus
//
//  Created Anik on 16/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignInViewController: UIViewController, SignInViewProtocol {

	var presenter: SignInPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
