//
//  SignInProtocols.swift
//  Plexus
//
//  Created Anik on 16/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SignInWireframeProtocol: class {
    func showTabMenuScreen(from view: SignInViewProtocol)
}
//MARK: Presenter -
protocol SignInPresenterProtocol: class {
    func showTabMenu()
}

//MARK: Interactor -
protocol SignInInteractorProtocol: class {

  var presenter: SignInPresenterProtocol?  { get set }
}

//MARK: View -
protocol SignInViewProtocol: class {

  var presenter: SignInPresenterProtocol?  { get set }
}
