# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Navigo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Navigo
    pod 'Firebase/Analytics'
    pod 'Firebase/Auth'
    pod 'GoogleMaps'
    pod 'GooglePlaces'
    pod 'Panels'
    pod 'InteractiveSideMenu'
    pod 'UPCarouselFlowLayout'
    pod 'Alamofire', '~> 5.0.0-beta.5'
end
