//
//  WalkThroughViewController.swift
//  Plexus
//
//  Created Anik on 16/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WalkThroughViewController: UIViewController, WalkThroughViewProtocol {

	var presenter: WalkThroughPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
