//
//  WalkThroughProtocols.swift
//  Plexus
//
//  Created Anik on 16/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol WalkThroughWireframeProtocol: class {

}
//MARK: Presenter -
protocol WalkThroughPresenterProtocol: class {

}

//MARK: Interactor -
protocol WalkThroughInteractorProtocol: class {

  var presenter: WalkThroughPresenterProtocol?  { get set }
}

//MARK: View -
protocol WalkThroughViewProtocol: class {

  var presenter: WalkThroughPresenterProtocol?  { get set }
}
