//
//  WalkThroughViewController.swift
//  Plexus
//
//  Created Anik on 16/8/19.
//  Copyright © 2019 A7Studio. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import TweenController

class WalkThroughViewController: UIViewController, WalkThroughViewProtocol, TutorialViewController {

    @IBOutlet var containerView: UIView!
    @IBOutlet var buttonsContainerView: UIView!
    @IBOutlet var pageControl: UIPageControl!
    
    private var hasAppeared = false
    private var tweenController: TweenController!
    private var scrollView: UIScrollView!
    
	var presenter: WalkThroughPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        if !hasAppeared {
            hasAppeared = true
            
            let (tc, scrollView) = TutorialBuilder.buildWithContainerViewController(self)
            self.tweenController = tc
            self.scrollView = scrollView
            self.scrollView.delegate = self
        }
    }

    private func updatePageControl() {
        pageControl.currentPage = Int(round(scrollView.contentOffset.x / containerView.frame.width))
    }
    
    @IBAction func skipButtonClicked(_ sender: Any) {
        print("skip button pressed")
        //go to profile view ready
        didReachedLastTutorial()
    }
    
    @IBAction func nextButtonClicked(_ sender: Any) {
        print("next button pressed")
        //go to next view
        //scrollView.twc_horizontalPageProgress = CGFloat(pageControl.currentPage + 1)
        var frame = scrollView.frame;
        let pageToGo = pageControl.currentPage + 1
        frame.origin.x = frame.size.width * CGFloat(pageToGo);
        frame.origin.y = 0;
        scrollView.scrollRectToVisible(frame, animated: true)
        pageControl.currentPage = pageControl.currentPage + 1
    }
    
    func didReachedLastTutorial() {
        print("did reached last tutorial")
        let storyBoard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
        let profileReadyViewController = storyBoard.instantiateViewController(withIdentifier: "profileReadyView") as! ProfileReadyViewController
        self.show(profileReadyViewController, sender: nil)
    }
}

extension WalkThroughViewController: UIScrollViewDelegate {
    
    func scrollViewDidScroll(_ scrollView: UIScrollView) {
        tweenController.update(progress: Double(scrollView.twc_horizontalPageProgress))
    }
    
    func scrollViewDidEndDecelerating(_ scrollView: UIScrollView) {
        updatePageControl()
    }
    
    func scrollViewDidEndDragging(_ scrollView: UIScrollView, willDecelerate decelerate: Bool) {
        if !decelerate {
            updatePageControl()
        }
    }
}
